; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir = client/include
src_dir = client/src
lib_dir = client/lib
default_envs = example1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
; monitor_filters = esp32_exception_decoder
lib_ldf_mode = deep+
lib_deps = 
	zinggjm/GFX_Root @ ^2.0.0
	; zinggjm/GxEPD2 @ ^1.6.6
	file://./GxEPD2	; for development, use local copy of GxEPD2 library with my improvements
	arcao/Syslog @ ^2.0.0
	https://github.com/tzapu/WiFiManager.git
	bblanchon/ArduinoJson @ ^6.20.1
build_flags =
    -Wl,--print-memory-usage
; optional: always show size summary
; targets = size

[board_laskakit_espink_v3_5]
; LaskaKit ESPink v3.5 - enable on GPIO47, voltage divider on GPIO 9
; https://www.laskakit.cz/laskakit-espink-esp32-e-paper-pcb-antenna/?variantId=12419
; ESP32-S3 N16R8, 16MB flash, 8MB PSRAM
board = esp32-s3-devkitc-1
board_build.flash_size = 16MB
board_build.psram_size = 8MB
upload_speed = 921600

[board_laskakit_espink_v2_5]
; ESP controller board: ESPink v2.5 from LaskaKit.cz
; https://github.com/LaskaKit/ESPink/blob/main/HW/old/ESPink_v2_5.pdf
; ESP32, 4MB flash, no PSRAM
board = esp32dev

[board_ezsbc_esp32]
# ESP32, 4MB flash, no PSRAM
board = esp32dev

[env:example1]
extends = board_laskakit_espink_v2_5
build_flags = 
	${env.build_flags}
	-Iclient/include/boards/examples/blackandwhite_GDEW075T7_and_laskakit_ESPink_v2.5
	-DSPLIT_DISPLAY_INTO_N_PAGES=2

[env:example2]
extends = board_laskakit_espink_v3_5
build_flags = 
	${env.build_flags}
	-Iclient/include/boards/examples/3color_GDEW075Z08_and_laskakit_ESPink_v3.5
	-DSPLIT_DISPLAY_INTO_N_PAGES=1

[env:example3]
extends = board_laskakit_espink_v2_5
build_flags = 
 	${env.build_flags}
	-Iclient/include/boards/examples/4color_GDEM075F52_and_laskakit_ESPink_v2.5
	-DSPLIT_DISPLAY_INTO_N_PAGES=2


; ================================================================
; Automated tests:
; ================================================================
[tests_base]
board = esp32dev

[env:test1]
extends = tests_base
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=1
	-Iclient/include/boards/tests/1

[env:test2]
extends = tests_base, board_laskakit_espink_v3_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=1
	-Iclient/include/boards/tests/2

[env:test3]
extends = tests_base, board_laskakit_espink_v2_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=2
	-Iclient/include/boards/tests/3 

[env:test4]
extends = tests_base, board_ezsbc_esp32
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=2
	-Iclient/include/boards/tests/4_remap_spi


; ================================================================
; My real boards:
; ================================================================
[env:michal_calendar1]
extends = board_ezsbc_esp32
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=2
	-Iclient/include/boards/michal/calendar1_portal
upload_port = esp15-portal.local

[env:michal_calendar2]
extends = board_laskakit_espink_v2_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=2
	-Iclient/include/boards/michal/calendar2_weather
upload_port = esp36-weather.local

[env:michal_calendar3]
extends = board_laskakit_espink_v2_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=2
	-Iclient/include/boards/michal/calendar3_family_calendar
upload_port = esp33-calendar.local

[env:michal_calendar4]
extends = board_laskakit_espink_v2_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=2
	-Iclient/include/boards/michal/calendar4_xkcd
upload_port = esp34-xkcd.local

[env:michal_calendar5]
extends = board_laskakit_espink_v2_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=2
	-Iclient/include/boards/michal/epaper5_bwry
upload_port = esp35-epaper5.local

[env:michal_calendar6]
extends = board_laskakit_espink_v3_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=1
	-Iclient/include/boards/michal/epaper6
upload_port = esp64-epaper6.local

[env:michal_calendar7]
extends = board_laskakit_espink_v3_5
build_flags = 
	${env.build_flags}
	-DSPLIT_DISPLAY_INTO_N_PAGES=1
	-Iclient/include/boards/michal/epaper7
upload_port = esp65-epaper7.local
