; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
include_dir = client/include
src_dir = client/src
lib_dir = client/lib
default_envs = example1

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+
lib_deps = 
	zinggjm/GFX_Root @ ^2.0.0
	zinggjm/GxEPD2 @ ^1.6.6
	arcao/Syslog @ ^2.0.0
	https://github.com/tzapu/WiFiManager.git
	bblanchon/ArduinoJson @ ^6.20.1
	madhephaestus/ESP32AnalogRead @ ^0.2.1

[env:example1]
board = esp32dev
build_flags = -Iclient/include/boards/examples/black_and_white_GDEH0213B72_and_laskakit_ESPink_v2.5

[env:example2]
board = esp32dev
build_flags = -Iclient/include/boards/examples/3color_GDEW075Z08_and_laskakit_ESPink_v3.5

[env:example3]
board = esp32dev
build_flags = -Iclient/include/boards/examples/4color_GDEM075F52_and_laskakit_ESPink_v2.5



; ================================================================
; Automated tests:
; ================================================================
[tests_base]
board = esp32dev

[env:test1]
extends = tests_base
build_flags = -Iclient/include/boards/tests/1

[env:test2]
extends = tests_base
build_flags = -Iclient/include/boards/tests/2

[env:test3]
extends = tests_base
build_flags = -Iclient/include/boards/tests/3

[env:test4]
extends = tests_base
build_flags = -Iclient/include/boards/tests/4_remap_spi


; ================================================================
; My real boards:
; ================================================================
[env:michal_calendar1]
board = esp32dev
build_flags = -Iclient/include/boards/michal/calendar1_portal
upload_port = esp15-portal.local

[env:michal_calendar2]
board = esp32dev
build_flags = -Iclient/include/boards/michal/calendar2_weather
upload_port = esp36-weather.local

[env:michal_calendar3]
board = esp32dev
build_flags = -Iclient/include/boards/michal/calendar3_family_calendar
upload_port = esp33-calendar.local

[env:michal_calendar4]
board = esp32dev
build_flags = -Iclient/include/boards/michal/calendar4_xkcd
upload_port = esp34-xkcd.local

[env:michal_calendar5]
board = esp32dev
build_flags = -Iclient/include/boards/michal/epaper5_bwry
upload_port = esp35-epaper5.local

[env:test_GxEPD2_750c_ZJY]
board = esp32-s3-devkitc-1
# very verbose debug output
; build_flags = -DCORE_DEBUG_LEVEL=5
build_flags = -Iclient/include/boards/esp64_test
; upload_port = esp64.local
upload_port = COM4
upload_speed = 921600
monitor_port = COM4
monitor_speed = 115200


