// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCalendarServer.Data;

#nullable disable

namespace PortalCalendarServer.Migrations
{
    [DbContext(typeof(CalendarContext))]
    [Migration("20260220205626_UpdateExistingCalendars")]
    partial class UpdateExistingCalendars
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Cache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("creator");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB")
                        .HasColumnName("data");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("expires_at")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Creator", "Key" }, "cache_creator_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ExpiresAt", "Creator" }, "cache_expires_at");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.ColorPaletteLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ColorVariantCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("color_variant_code");

                    b.Property<string>("EpdColorCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("epd_color_code");

                    b.HasKey("Id");

                    b.HasIndex("EpdColorCode");

                    b.HasIndex("ColorVariantCode", "EpdColorCode")
                        .IsUnique();

                    b.ToTable("color_palette_links", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorVariantCode = "BW",
                            EpdColorCode = "black"
                        },
                        new
                        {
                            Id = 2,
                            ColorVariantCode = "BW",
                            EpdColorCode = "white"
                        },
                        new
                        {
                            Id = 3,
                            ColorVariantCode = "BWY",
                            EpdColorCode = "black"
                        },
                        new
                        {
                            Id = 4,
                            ColorVariantCode = "BWY",
                            EpdColorCode = "white"
                        },
                        new
                        {
                            Id = 5,
                            ColorVariantCode = "BWY",
                            EpdColorCode = "yellow"
                        },
                        new
                        {
                            Id = 6,
                            ColorVariantCode = "BWR",
                            EpdColorCode = "black"
                        },
                        new
                        {
                            Id = 7,
                            ColorVariantCode = "BWR",
                            EpdColorCode = "white"
                        },
                        new
                        {
                            Id = 8,
                            ColorVariantCode = "BWR",
                            EpdColorCode = "red"
                        });
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.ColorVariant", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayTypeCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("display_type_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.HasIndex("DisplayTypeCode", "Name")
                        .IsUnique();

                    b.ToTable("color_variants", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "BW",
                            DisplayTypeCode = "BW",
                            Name = "Black and White"
                        },
                        new
                        {
                            Code = "BWY",
                            DisplayTypeCode = "3C",
                            Name = "Black, White, Yellow"
                        },
                        new
                        {
                            Code = "BWR",
                            DisplayTypeCode = "3C",
                            Name = "Black, White, Red"
                        });
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DisplayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DisplayId");

                    b.HasIndex(new[] { "Name", "DisplayId" }, "config_name_display")
                        .IsUnique();

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Display", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BorderBottom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_bottom");

                    b.Property<int>("BorderLeft")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_left");

                    b.Property<int>("BorderRight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_right");

                    b.Property<int>("BorderTop")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_top");

                    b.Property<string>("ColorVariantCode")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("color_variant");

                    b.Property<string>("DisplayTypeCode")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("display_type");

                    b.Property<string>("Firmware")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("firmware");

                    b.Property<double?>("Gamma")
                        .HasColumnType("NUMERIC(4,2)")
                        .HasColumnName("gamma");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("mac");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rotation");

                    b.Property<int?>("ThemeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("theme_id");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex("ColorVariantCode");

                    b.HasIndex("DisplayTypeCode");

                    b.HasIndex("ThemeId");

                    b.HasIndex(new[] { "Mac" }, "IX_displays_mac")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_displays_name")
                        .IsUnique();

                    b.ToTable("displays", (string)null);
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.DisplayType", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.Property<int>("NumColors")
                        .HasColumnType("INTEGER")
                        .HasColumnName("num_colors");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("display_types", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "BW",
                            Name = "Black and White",
                            NumColors = 2
                        },
                        new
                        {
                            Code = "3C",
                            Name = "3 Color",
                            NumColors = 3
                        });
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.EpdColor", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("code");

                    b.Property<string>("EpdPreviewHexValue")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("epd_preview_hex_value");

                    b.Property<string>("HexValue")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("hex_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("epd_colors", (string)null);

                    b.HasData(
                        new
                        {
                            Code = "black",
                            EpdPreviewHexValue = "111111",
                            HexValue = "000000",
                            Name = "Black"
                        },
                        new
                        {
                            Code = "white",
                            EpdPreviewHexValue = "dddddd",
                            HexValue = "FFFFFF",
                            Name = "White"
                        },
                        new
                        {
                            Code = "red",
                            EpdPreviewHexValue = "aa0000",
                            HexValue = "FF0000",
                            Name = "Red"
                        },
                        new
                        {
                            Code = "yellow",
                            EpdPreviewHexValue = "dddd00",
                            HexValue = "FFFF00",
                            Name = "Yellow"
                        });
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("display_name");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("file_name");

                    b.Property<bool>("HasCustomConfig")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_custom_config");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("FileName")
                        .IsUnique();

                    b.ToTable("themes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "Default",
                            FileName = "Default",
                            HasCustomConfig = false,
                            IsActive = true,
                            IsDefault = true,
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Portal Style Calendar with Icons",
                            FileName = "PortalStyleCalendarWithIcons",
                            HasCustomConfig = true,
                            IsActive = true,
                            IsDefault = false,
                            SortOrder = 100
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "Google Fit Weight with Calendar and Icons",
                            FileName = "GoogleFitWeightWithCalendarAndIcons",
                            HasCustomConfig = true,
                            IsActive = true,
                            IsDefault = false,
                            SortOrder = 200
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "Weather",
                            FileName = "WeatherForecast",
                            HasCustomConfig = false,
                            IsActive = true,
                            IsDefault = false,
                            SortOrder = 300
                        },
                        new
                        {
                            Id = 5,
                            DisplayName = "Multi-day Calendar",
                            FileName = "MultidayCalendar",
                            HasCustomConfig = true,
                            IsActive = true,
                            IsDefault = false,
                            SortOrder = 400
                        },
                        new
                        {
                            Id = 6,
                            DisplayName = "XKCD",
                            FileName = "XKCD",
                            HasCustomConfig = false,
                            IsActive = true,
                            IsDefault = false,
                            SortOrder = 500
                        },
                        new
                        {
                            Id = 7,
                            DisplayName = "Test - Color Wheel",
                            FileName = "Test",
                            HasCustomConfig = false,
                            IsActive = true,
                            IsDefault = false,
                            SortOrder = 10000
                        });
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.ColorPaletteLink", b =>
                {
                    b.HasOne("PortalCalendarServer.Models.DatabaseEntities.ColorVariant", "ColorVariant")
                        .WithMany()
                        .HasForeignKey("ColorVariantCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortalCalendarServer.Models.DatabaseEntities.EpdColor", "EpdColor")
                        .WithMany()
                        .HasForeignKey("EpdColorCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorVariant");

                    b.Navigation("EpdColor");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.ColorVariant", b =>
                {
                    b.HasOne("PortalCalendarServer.Models.DatabaseEntities.DisplayType", "DisplayType")
                        .WithMany("ColorVariants")
                        .HasForeignKey("DisplayTypeCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DisplayType");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Config", b =>
                {
                    b.HasOne("PortalCalendarServer.Models.DatabaseEntities.Display", "Display")
                        .WithMany("Configs")
                        .HasForeignKey("DisplayId")
                        .IsRequired();

                    b.Navigation("Display");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Display", b =>
                {
                    b.HasOne("PortalCalendarServer.Models.DatabaseEntities.ColorVariant", "ColorVariant")
                        .WithMany("Displays")
                        .HasForeignKey("ColorVariantCode")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PortalCalendarServer.Models.DatabaseEntities.DisplayType", "DisplayType")
                        .WithMany("Displays")
                        .HasForeignKey("DisplayTypeCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PortalCalendarServer.Models.DatabaseEntities.Theme", "Theme")
                        .WithMany("Displays")
                        .HasForeignKey("ThemeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ColorVariant");

                    b.Navigation("DisplayType");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.ColorVariant", b =>
                {
                    b.Navigation("Displays");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Display", b =>
                {
                    b.Navigation("Configs");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.DisplayType", b =>
                {
                    b.Navigation("ColorVariants");

                    b.Navigation("Displays");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.DatabaseEntities.Theme", b =>
                {
                    b.Navigation("Displays");
                });
#pragma warning restore 612, 618
        }
    }
}
