// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCalendarServer.Data;

#nullable disable

namespace PortalCalendarServer.Migrations
{
    [DbContext(typeof(CalendarContext))]
    [Migration("20260214150117_UpdateModelNamespace")]
    partial class UpdateModelNamespace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("PortalCalendarServer.Models.Entities.Cache", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("creator");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB")
                        .HasColumnName("data");

                    b.Property<DateTime>("ExpiresAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasColumnName("expires_at")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("key");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Creator", "Key" }, "cache_creator_key")
                        .IsUnique();

                    b.HasIndex(new[] { "ExpiresAt", "Creator" }, "cache_expires_at");

                    b.ToTable("cache", (string)null);
                });

            modelBuilder.Entity("PortalCalendarServer.Models.Entities.Config", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DisplayId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("display_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("DisplayId");

                    b.HasIndex(new[] { "Name", "DisplayId" }, "config_name_display")
                        .IsUnique();

                    b.ToTable("config", (string)null);
                });

            modelBuilder.Entity("PortalCalendarServer.Models.Entities.Display", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("BorderBottom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_bottom");

                    b.Property<int>("BorderLeft")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_left");

                    b.Property<int>("BorderRight")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_right");

                    b.Property<int>("BorderTop")
                        .HasColumnType("INTEGER")
                        .HasColumnName("border_top");

                    b.Property<string>("ColorType")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("colortype");

                    b.Property<string>("Firmware")
                        .HasColumnType("VARCHAR")
                        .HasColumnName("firmware");

                    b.Property<double?>("Gamma")
                        .HasColumnType("NUMERIC(4,2)")
                        .HasColumnName("gamma");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("mac");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR")
                        .HasColumnName("name");

                    b.Property<int>("Rotation")
                        .HasColumnType("INTEGER")
                        .HasColumnName("rotation");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Mac" }, "IX_displays_mac")
                        .IsUnique();

                    b.HasIndex(new[] { "Name" }, "IX_displays_name")
                        .IsUnique();

                    b.ToTable("displays", (string)null);
                });

            modelBuilder.Entity("PortalCalendarServer.Models.Entities.Config", b =>
                {
                    b.HasOne("PortalCalendarServer.Models.Entities.Display", "Display")
                        .WithMany("Configs")
                        .HasForeignKey("DisplayId")
                        .IsRequired();

                    b.Navigation("Display");
                });

            modelBuilder.Entity("PortalCalendarServer.Models.Entities.Display", b =>
                {
                    b.Navigation("Configs");
                });
#pragma warning restore 612, 618
        }
    }
}
