#!/bin/sh

# To be run after the deploy

cd server
carton install --deployment --cached
npm install
sudo systemctl reload portal_calendar-ui.service
sudo systemctl reload portal_calendar-puppeteer.service
#sudo systemctl restart portal_calendar-minion.service
scripts/generate_img_from_web