#!/usr/bin/env perl

use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use Mojolicious::Lite;
use DDP;
use DateTime;

# Static files are automatically served from the /public subfolder.

get '/ping' => sub {
    my $self   = shift;
    my $result = {};
    return $self->render(json => { status => 'ok' });
};

get '/calendar/html' => sub {
    my $self   = shift;

    #return $self->render(json => { status => 'failure', message => 'FIXME TODO' });

    my $dt = DateTime->now();
    #$dt = DateTime->new(year => '2023', month => 7, day => 31);  # mock
    $dt->set_locale('en-US');

    #p $dt;
    $self->stash(date => $dt);

    return $self->render(template => 'calendar', format => 'html');
};

get '/calendar/png' => sub {
    my $self   = shift;

    my $bytes = 'foobar';
    return $self->render(data => $bytes, format => 'png');
};

get '/' => sub {
    my $self = shift;

    #return $self->render(text => 'test', format => 'html');
    return $self->render(template => 'test', format => 'html');
};

app->secrets(['My very secret passphsasdfi903478ty90 e8gd opasjf23[f- rase.']);   # FIXME  FIXME
plugin 'TagHelpers';
app->start;