requires 'FindBin';
requires 'Mojolicious::Lite';
requires 'Mojolicious::Plugin::RenderFile';
requires 'Mojolicious::Plugin::TagHelpers';
requires 'Mojolicious::Plugin::Config';
requires 'DDP';
requires 'DateTime';
requires 'DateTime::Format::Strptime';
requires 'File::Slurp';
requires 'Imager';
requires 'Text::Unidecode';
requires 'List::Util';
requires 'Readonly';


