// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalCalendarServer.Data;

#nullable disable

namespace PortalCalendarServer.Data.Migrations.Session
{
    [DbContext(typeof(SessionContext))]
    partial class SessionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("PortalCalendarServer.Data.AuthSession", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("VARCHAR(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("DATETIME")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("Value")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_auth_sessions_expires_at");

                    b.ToTable("auth_sessions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
