#!/usr/bin/env perl

use strict;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use Mojolicious::Lite;
use DDP;
use Storable;
use Mojo::Util qw(b64_decode);

use PortalCalendar;
use PortalCalendar::Config;
use PortalCalendar::Schema;
use PortalCalendar::Integration::iCal;
use PortalCalendar::Integration::OpenWeather;

helper schema => sub { state $schema = PortalCalendar::Schema->connect('dbi:SQLite:local/calendar.db') };

foreach my $row (app->schema->resultset('Cache')->search(undef, { order_by => 'id' })->all) {
    my $perldata = Storable::thaw(b64_decode($row->data));
    p $perldata, as => 'cache row id "' . $row->id . '":', output => 'stdout';
    print "\n";
}
