#!/bin/bash

# load ENV settings
dir=$(dirname $0)
set -a
. $dir/../.env
set +a

# run the webserver
echo "starting server in $MOJO_MODE mode"
if [ $MOJO_MODE == "development" ]; then
    cd $dir/.. && morbo -v -l 'http://*:8081' -w templates -w lib app
else
    cd $dir/.. && carton exec ./app daemon -m $MOJO_MODE -l "http://[::]:${PORT}"
fi
