#!/bin/bash

dir=$(dirname $0)
if [ "$1" == "--without-carton" ]; then
    cd $dir/.. && ./scripts/portal_calendar minion worker -j 1
else
    cd $dir/.. && carton exec -- ./scripts/portal_calendar minion worker -j 1
fi
