#!/bin/bash

dir=$(dirname $0)
if [ "$1" == "--without-carton" ]; then
    cd $dir/.. && morbo -v -l "http://*:8081" -w templates -w lib scripts/portal_calendar
else
    cd $dir/.. && carton exec -- hypnotoad ./scripts/portal_calendar
fi
